version: '3'

name: books-api-env

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books_api
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.2.4
    container_name: redis_container
    ports:
      - "6379:6379"