version: '3'

name: books-api-demo

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books_api
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - books_api_network

  redis:
    image: redis:7.2.4
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - books_api_network

  books-api:
    container_name: books_api_container
    build: ../
    ports:
      - "8080:8080"
    environment:
      - APP_PROFILE=demo
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ENABLE_REDIS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - books_api_network

networks:
  books_api_network:
    driver: bridge