version: '3'

name: books_api_project

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books_api
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql